<?php
declare(strict_types=1);

/**
 * QUEM JÁ FEZ — os vídeos de referência de cada formato, por nicho.
 *
 * Saiu das checklists do quadro público "Formatos Criativos de Conteúdo
 * [Alunos]" (trello.com/b/VOx6su53), onde cada card de APLICAÇÃO carrega duas
 * listas: os criadores que viralizaram com o formato e o mesmo formato aplicado
 * em nichos diferentes. São 362 links, cobrindo os 16 formatos que vieram do
 * curso.
 *
 * POR QUE ISSO É O QUE FALTAVA. "Grave um Dinamismo" é uma instrução que não
 * diz o que filmar; "grave um Dinamismo, e olha aqui quem já fez isso falando
 * de política" é. O resto da Oficina responde QUAL formato e COMO ele se grava
 * — esta lista responde COM O QUÊ, que é onde a página em branco costuma
 * ganhar.
 *
 * FICA SEPARADO DO CATÁLOGO de propósito, como as capas: `oficina-catalogo.php`
 * é o que o formato É, e este arquivo é o que os outros fizeram com ele. São
 * 363 linhas que ninguém quer atravessar para corrigir a dica de gravação.
 *
 * O `nicho` é o rótulo como ele está no quadro, em caixa alta e sem
 * padronização — "POLÍTICA", "ATIVISMO SOCIAL E POLÍTICO", "PROJETO SOCIAL" são
 * três rótulos e não um. Padronizar seria inventar uma taxonomia que a fonte
 * não tem; quem ordena por proximidade é `NICHOS_PROXIMOS`, que casa por
 * pedaço de texto e não por chave.
 *
 * Os links `criadoresdofuturo.short.gy` são encurtadores do próprio curso e
 * levam ao Instagram. Ficam como estão: reescrevê-los para o destino final
 * quebraria no dia em que o curso trocar o alvo.
 */

/**
 * Os rótulos que importam para quem faz conteúdo de campanha.
 *
 * Casam por PEDAÇO do rótulo, e é essa a razão de serem fragmentos e não
 * palavras inteiras: o quadro traz "ATIVISMO SOCIAL E POLÍTICO" e "POLÍTICA" em
 * cards diferentes, e uma lista de chaves exatas perderia um dos dois.
 */
const NICHOS_PROXIMOS = ['POLÍT', 'POLIT', 'ATIVIS', 'SOCIAL', 'EDUCA', 'DIREITO', 'SAÚDE', 'SAUDE', 'NOTÍC', 'NOTIC', 'JORNAL'];

/** Os vídeos de referência, por formato. Formato fora daqui simplesmente não tem. */
const REFERENCIAS_OFICINA = [
    'bastidores' => [
        ['nicho' => 'MÚSICA', 'url' => 'https://www.instagram.com/p/DLEiP-VsE5_/'],
        ['nicho' => 'CRIADOR CRIATIVO', 'url' => 'https://www.instagram.com/reel/DKjd50tSgto/?igsh=MW1lZDZtaWMwMXowMA=='],
        ['nicho' => 'FILMMAKER', 'url' => 'https://www.instagram.com/reel/DKjx4qZSLO-/?igsh=MTFwc3Q0YzZxMGo3cA=='],
        ['nicho' => 'CRIADOR CRIATIVO', 'url' => 'https://www.instagram.com/reel/DHYgn23vRAz/?igsh=MTExbHVydmoxZ2luNA=='],
        ['nicho' => 'FILMMAKER', 'url' => 'https://www.instagram.com/reel/DHR1NnMSDLM/?igsh=eGk2Z3lnOWNqZGF1'],
        ['nicho' => 'FOTÓGRAFO', 'url' => 'https://www.instagram.com/reel/DHL8jUQu16D/?igsh=NHRiY3hhYW5zYmhp'],
        ['nicho' => 'LOJA DE CARRO', 'url' => 'https://www.instagram.com/reel/DJJ5R_-KhkL/?igsh=MXJmN3g1cG91bWRxbA=='],
        ['nicho' => 'FOTOGRAFIA', 'url' => 'https://www.instagram.com/reel/DGlk2GQuK4S/?igsh=M3hkcGZ1NGllZnk5'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DJj2BPBNQqG/?igsh=OGluZTQ1YndodGxh'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DHZIn7RSWYO/?igsh=MWVxbjdleWV6MXVzcQ=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DJwy6PACz3w/?igsh=ZHNoZmVrdWhiZ2J0'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DLtsZEuve4n/?igsh=MTV6ZWJrMDkxZ21vNw=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DJMne1zCzyq/?igsh=YmhheGF3MXhhdnZ0'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKg2gkrqUxL/?igsh=MW5uaDV5aGFqNjJjdg=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKuDAsbSnyn/?igsh=ZXFob3B6a254dHJ4'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DMLU2n8IRDo/?igsh=anJ0MnN1ZzdrcWw5'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DHKyDZUSoaH/?igsh=MXY0MmZseXNkcGViZQ=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DJG4tVppHyQ/?igsh=MTJwN2J0ajQ0YTBzaQ=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DGV4r_Yz8hh/?igsh=ajJwZGdwZ2c5dTUz'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DMXfUqctEpF/?igsh=MTB5NXY2M25zZXM0Yg=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKT8uH3K47Z/?igsh=MXdiZnBkNWltYmd5'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DImSZ4tMVdk/?igsh=b3Y5MTdybHppNWlq'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DLfm2OxCzTG/?igsh=YnJucWE5MnhnMDdl'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKHnzP5o2bY/?igsh=MTZ2NjJhbWdvanJ5Yg=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DIHngMkvEZt/?igsh=NHozb3o3MnNrdDBm'],
    ],
    'storytelling-visual' => [
        ['nicho' => 'RELACIONAMENTO', 'url' => 'https://criadoresdofuturo.short.gy/contentmachine'],
        ['nicho' => 'RELACIONAMENTO', 'url' => 'https://criadoresdofuturo.short.gy/felipebustamante'],
        ['nicho' => 'AUTOCONHECIMENTO', 'url' => 'https://criadoresdofuturo.short.gy/ninabaiocchi2'],
        ['nicho' => 'INTELIGÊNCIA ARTIFICIAL', 'url' => 'https://criadoresdofuturo.short.gy/dennishan'],
        ['nicho' => 'HUMOR', 'url' => 'https://criadoresdofuturo.short.gy/evandrorodrigues'],
        ['nicho' => 'CRISTIANISMO', 'url' => 'https://www.instagram.com/p/DKpRBwCRiRE/'],
        ['nicho' => 'VIAGEM', 'url' => 'https://www.instagram.com/p/DMs_ojlMm_9/'],
        ['nicho' => 'AUTOCONHECIMENTO', 'url' => 'https://www.instagram.com/reel/DM8Tt-cOBNT/?igsh=MWFsaHVmczJjYjE4cw%3D%3D'],
        ['nicho' => 'CRIATIVIDADE', 'url' => 'https://www.instagram.com/p/DGQmkIYJXFO/'],
        ['nicho' => 'CICLISMO', 'url' => 'https://www.instagram.com/reel/DKCm9TTtH7l/?igsh=YjI3Zjczbnhmdjhv'],
        ['nicho' => 'UNIVERSO FEMININO', 'url' => 'https://www.instagram.com/reel/DJCMdwVJB6k/?igsh=OGZpdXF4d3dhOHlu'],
        ['nicho' => 'NUTRIÇÃO', 'url' => 'https://www.instagram.com/p/DIgRFfPuJ7j/'],
        ['nicho' => 'TDAH', 'url' => 'https://www.instagram.com/p/DA1AFv4Og2q/'],
        ['nicho' => 'PSICOEDUCAÇÃO', 'url' => 'https://www.instagram.com/p/DNEdTQKMrmI/'],
        ['nicho' => 'OBJETO ANIMADO', 'url' => 'https://www.instagram.com/p/DJ2YMGvP3Wz/'],
        ['nicho' => 'BIBLIA', 'url' => 'https://www.instagram.com/p/DFMknzvye8Q/'],
        ['nicho' => 'DESENHOS', 'url' => 'https://www.instagram.com/p/DLVgyS1xhxs/'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/hanahfranklin2'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/alexgriswold'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DDHtYnzRbZe/'],
    ],
    'the-office' => [
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/felipebustamante2'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/rafaelreis'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/franklinmedrado'],
        ['nicho' => 'LANCHONETE', 'url' => 'https://criadoresdofuturo.short.gy/suzaneiano'],
        ['nicho' => 'PETS', 'url' => 'https://criadoresdofuturo.short.gy/malcomsalsicha'],
        ['nicho' => 'HUMOR', 'url' => 'https://criadoresdofuturo.short.gy/rafaelreis2'],
        ['nicho' => 'CASA', 'url' => 'https://criadoresdofuturo.short.gy/rafaelreis3'],
        ['nicho' => 'RELACIONAMENTO', 'url' => 'https://criadoresdofuturo.short.gy/hanahfranklin3'],
        ['nicho' => 'PUBLI', 'url' => 'https://www.instagram.com/reel/DLYNm2SRTW7/?igsh=MW9jNHJsZWFlcjJ6dg=='],
        ['nicho' => 'COMIDA JAPONESA', 'url' => 'https://www.instagram.com/reel/C2YdnWrOrpT/?igsh=MTBxdWM0N29tZGs3Nw=='],
    ],
    'comparacao' => [
        ['nicho' => 'NEGÓCIOS', 'url' => 'https://criadoresdofuturo.short.gy/delmateodora'],
        ['nicho' => 'EMAGRECIMENTO', 'url' => 'https://criadoresdofuturo.short.gy/gabifrienzzo'],
        ['nicho' => 'FITNESS', 'url' => 'https://criadoresdofuturo.short.gy/carolborba'],
        ['nicho' => 'MARKETING', 'url' => 'https://criadoresdofuturo.short.gy/sequelmedia'],
        ['nicho' => 'MODA', 'url' => 'https://criadoresdofuturo.short.gy/gabifrienzzo2'],
        ['nicho' => 'NUTRIÇÃO', 'url' => 'https://criadoresdofuturo.short.gy/lainemoser'],
        ['nicho' => 'ROTINA E PRODUTIVIDADE', 'url' => 'https://criadoresdofuturo.short.gy/carolborba2'],
        ['nicho' => 'PRODUTO FÍSICO', 'url' => 'https://criadoresdofuturo.short.gy/brunacabral'],
        ['nicho' => 'RELACIONAMENTO', 'url' => 'https://criadoresdofuturo.short.gy/juliasaraivavieira2'],
        ['nicho' => 'TERAPIA (ALUNA)', 'url' => 'https://www.instagram.com/reel/DH6ywGUhu0M/?igsh=aGx4cHJ0dTRwaHY1'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/tammyparra'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/paulapavan'],
    ],
    'tela-verde' => [
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DC7y_rPN9ep/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DCFVQdxubpp/'],
        ['nicho' => 'COMIDA', 'url' => 'https://www.instagram.com/reel/DHoXGEzgWlw/?utm_source=ig_web_copy_link'],
        ['nicho' => 'CIÊNCIA', 'url' => 'https://www.instagram.com/reel/DImlIZnyDA-/'],
        ['nicho' => 'INTELIGÊNCIA ARTIFICIAL', 'url' => 'https://www.instagram.com/reel/DDskSFJxHEJ/'],
        ['nicho' => 'HUMOR', 'url' => 'https://www.instagram.com/p/DDihRNtM30x/'],
        ['nicho' => 'CORRIDA (ALUNA)', 'url' => 'https://www.instagram.com/reel/DM_TiV-gXuO/?igsh=Nnd4ZzJiNGx4dDEx'],
        ['nicho' => 'ACADEMIA', 'url' => 'https://www.instagram.com/p/DNTOgD1RwvX/'],
        ['nicho' => 'POLÍTICA', 'url' => 'https://www.instagram.com/p/DMxw05BRsF5/'],
        ['nicho' => 'BIOLOGIA', 'url' => 'https://www.instagram.com/reel/DF3BbcfODl_/'],
        ['nicho' => 'RELACIONAMENTO', 'url' => 'https://www.instagram.com/p/DN6Z6drjznO/'],
        ['nicho' => 'CURIOSIDADES', 'url' => 'https://www.instagram.com/p/DLObIJARchz/'],
        ['nicho' => 'CABELEIREIRA', 'url' => 'https://www.instagram.com/reel/DJaU4FiRgvu/?igsh=MWd4cXAxeWxuY2U0Zw=='],
        ['nicho' => 'DESIGN', 'url' => 'https://www.instagram.com/reel/DLVrz1Mu1ab/?igsh=cDBmc3l1N2FrcHhj'],
        ['nicho' => 'ARQUITETURA', 'url' => 'https://www.instagram.com/reel/DIGgp8_OTcr/?igsh=a2JkMmYwZGx0OTF4'],
        ['nicho' => 'REACT', 'url' => 'https://www.instagram.com/reel/DKGQ2QoRd2c/?igsh=ZHFpdTgxdmR3em9z'],
        ['nicho' => 'E-COMMERCE', 'url' => 'https://www.instagram.com/p/C97RCpauLgM/'],
        ['nicho' => 'DESENVOLVIMENTO INFANTIL', 'url' => 'https://www.instagram.com/p/C88ORGEIUcP/'],
        ['nicho' => 'CINEMA/CRÍTICA', 'url' => 'https://www.instagram.com/p/DKLNjGUoMc5/'],
        ['nicho' => 'CULTURA NIPO-BRASILEIRA', 'url' => 'https://www.instagram.com/p/DJ7amB9RlVF/'],
    ],
    'dinamismo' => [
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/annabelmachado'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/bomtalvao'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DHl9m8XygOi/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DJFa67fvHyd/?igsh=MXIyNmVrbG1vNXpzMA%3D%3D'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/C_HRVZaN10v/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DB095pvpVxz/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DNA6yUFuhV5/?igsh=dWthODVydXYyam5y'],
        ['nicho' => 'PUBLI', 'url' => 'https://www.instagram.com/p/DMLoMypufnU/'],
        ['nicho' => 'AMIZADES', 'url' => 'https://criadoresdofuturo.short.gy/annabelmachado1'],
        ['nicho' => 'MODA', 'url' => 'https://criadoresdofuturo.short.gy/maluborges1'],
        ['nicho' => 'MODA', 'url' => 'https://criadoresdofuturo.short.gy/gabimoretti2'],
        ['nicho' => 'EVOLUÇÃO PESSOAL', 'url' => 'https://www.instagram.com/reel/DMObTfayO2h/?igsh=MWg3ZGJiMGFpZXVlMA%3D%3D'],
        ['nicho' => 'MARKETING', 'url' => 'https://www.instagram.com/reels/DLbBJZMAcdu/'],
        ['nicho' => 'DESIGN', 'url' => 'https://www.instagram.com/reel/DI3_Wx5RndR/?igsh=cG5uNTNyNnR0b2Fp'],
    ],
    'narrado' => [
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/jhennykeller2'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/C_Lbe1wO1fk/?igsh=MWh4MmcwaG52eXFhdA=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DJxQ488uRbT/?igsh=MTJ4ZXg2dHR4czM3Mw=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DL0p6JFRc1n/?igsh=MTN6YThidW9hbzA5Zg=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DIfb_T6MFi6/?igsh=MXRyOW85Njh6YXMwNw=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DMEFW3TOF0C/?igsh=MTQ4amVvNmx1NXh4aw=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DN008Cz0Gua/'],
        ['nicho' => 'ARQUITETURA', 'url' => 'https://criadoresdofuturo.short.gy/theulynreis'],
        ['nicho' => 'PETS', 'url' => 'https://www.instagram.com/reel/DN0ppKm3Paj/?igsh=OGt0cHBncXE3NWs3'],
        ['nicho' => 'PRODUTO FISICO', 'url' => 'https://criadoresdofuturo.short.gy/isabelylarissa'],
        ['nicho' => 'CORRIDA', 'url' => 'https://criadoresdofuturo.short.gy/eunaddya'],
        ['nicho' => 'AUTOCONHECIMENTO', 'url' => 'https://www.instagram.com/reel/C-NnOBrhTM1/?igsh=OW5kcDZtb3RjMmVk'],
        ['nicho' => 'DESENVOLVIMENTO PESSOAL', 'url' => 'https://criadoresdofuturo.short.gy/ralphkhoury'],
        ['nicho' => 'MOTIVAÇÃO', 'url' => 'https://criadoresdofuturo.short.gy/shakkhiee'],
        ['nicho' => 'PRODUTIVIDADE', 'url' => 'https://criadoresdofuturo.short.gy/luckyegg'],
        ['nicho' => 'EDIÇÃO DE VÍDEO', 'url' => 'https://criadoresdofuturo.short.gy/happywithmeg'],
        ['nicho' => 'VIAGEM', 'url' => 'https://www.instagram.com/reel/DOZeTYED2Co/?igsh=MW45aWhzOGVwaXNmdQ=='],
        ['nicho' => 'DESENHO', 'url' => 'https://www.instagram.com/reel/C5O_Hp8JXVS/?igsh=MXZndTR1Ymk1eXoxZQ=='],
        ['nicho' => 'LIVROS', 'url' => 'https://www.instagram.com/reel/DLSFmTvRoTw/?igsh=czAyN2hibzM4dzZn'],
        ['nicho' => 'EMAGRECIMENTO', 'url' => 'https://www.instagram.com/reel/DOMn9PXDfWc/?igsh=dG4xeXgwZDBjYXc5'],
        ['nicho' => 'MATERNIDADE', 'url' => 'https://www.instagram.com/reel/DKdRlfqv4SG/?igsh=NWY0c2FvM21rNHA5'],
        ['nicho' => 'BARBEIRO(A)', 'url' => 'https://www.instagram.com/reel/DNgDHtJNCd2/?igsh=MXd1NXY3OGFhYXFtdg=='],
        ['nicho' => 'HIGIENIZADOR DE SOFÁS', 'url' => 'https://www.instagram.com/reel/DJC3sWcy9Oe/?igsh=MTFnNmFldzc3NTN4ZQ=='],
        ['nicho' => 'ARTE', 'url' => 'https://www.instagram.com/reel/DKnhAwExybO/?igsh=MzBwMHo2ajQwdjJt'],
        ['nicho' => 'PETSHOP', 'url' => 'https://www.instagram.com/reel/DNtBITr3Lmj/?igsh=MTMzeG5tejVqMzcwOA=='],
        ['nicho' => 'REFORMA', 'url' => 'https://www.instagram.com/reel/DNGZKSxA_my/?igsh=MnhzbzFzcnVlOWQw'],
        ['nicho' => 'CONSTRUÇÃO', 'url' => 'https://www.instagram.com/reel/DH3xdNGuZmI/?igsh=NWdleTU5aTg2MHk1'],
        ['nicho' => 'FLORISTA', 'url' => 'https://www.instagram.com/reel/DLzchNmxBMh/?igsh=MThoNzludXlucHF6Nw=='],
        ['nicho' => 'PEDICURE', 'url' => 'https://www.instagram.com/reel/DM6dBRwpLGc/?igsh=ZG9td2phbTV1c3Qz'],
        ['nicho' => 'CABELEIREIRO', 'url' => 'https://www.instagram.com/reel/Ch7lcF4ALBb/?igsh=MTJob21rbGZzNm95Ng=='],
        ['nicho' => 'ALONGAMENTO DE UNHAS', 'url' => 'https://www.instagram.com/reel/DIcNZ2ZvkoP/?igsh=MTJ6d3lzdGg5dTBzeQ=='],
        ['nicho' => 'CAPINHAS DE CELULAR PERSONALIZADAS', 'url' => 'https://www.instagram.com/reel/DHYsZwoxLId/?igsh=MWI2M2RqcmF4dWkzZg=='],
        ['nicho' => 'MECÂNICA', 'url' => 'https://www.instagram.com/reel/DM8OkNhAma8/?igsh=ZTJzcmY5ajB1bmV2'],
        ['nicho' => 'CUIDADOS COM CASCO DE CAVALO', 'url' => 'https://www.instagram.com/reel/DH5_0rvR7-H/?igsh=cGk2MWxrM28wN3Rk'],
        ['nicho' => 'DETECTORISMO', 'url' => 'https://www.instagram.com/reel/DK713rav5ww/?igsh=MXBhY2Fld3ltZmZ3NQ=='],
        ['nicho' => 'CONFEITARIA', 'url' => 'https://www.instagram.com/reel/C_WUOxUvLk2/?igsh=MTFtOGVvNGZ2Y2x3OQ=='],
        ['nicho' => 'GRAFFITI', 'url' => 'https://www.instagram.com/reel/DJU_34JSJ_R/?igsh=dGdqMm1vNmV3bGs1'],
        ['nicho' => 'ESTÉTICA AUTOMOTIVA', 'url' => 'https://www.instagram.com/reel/DJEyXEKNt2w/?igsh=MWR3NXI4N3g4dGdpNQ=='],
        ['nicho' => 'LIMPEZA DE PISCINA', 'url' => 'https://www.instagram.com/reel/DJAcG68RLdn/?igsh=NnU5cjgwZGpjdXht'],
        ['nicho' => 'TREINAMENTO CANINO', 'url' => 'https://www.instagram.com/reel/DIhawFpTM5e/?igsh=MTJlZWo5ODl5c2tlNg=='],
        ['nicho' => 'MANEJO DE MORCEGO', 'url' => 'https://www.instagram.com/reel/DHweCWxS2CU/?igsh=ZW13cXNiamE0NTAy'],
        ['nicho' => 'PRODUTO DE LIMPEZA DE PISOS', 'url' => 'https://www.instagram.com/reel/DHtz1-6JboK/?igsh=MTZ6OXhhdndtaGRuZA=='],
        ['nicho' => 'BIÓLOGO', 'url' => 'https://www.instagram.com/reel/DLyFSWNySig/?igsh=MWo0ZHU4aThkeGsxOQ=='],
        ['nicho' => 'QUÍMICA', 'url' => 'https://www.instagram.com/reel/DJkNDMcPlpQ/?igsh=d3M3cGRpaWFlczk0'],
        ['nicho' => 'CARICATURA', 'url' => 'https://www.instagram.com/reel/DOKRZTyD52l/?igsh=MXQ4YTh1ZnNjeHNtcw=='],
        ['nicho' => 'PUBLI', 'url' => 'https://www.instagram.com/reel/DKzhiF7shNX/?igsh=MXI2c2VkcnQzMHlvOA=='],
        ['nicho' => 'TATUAGEM', 'url' => 'https://www.instagram.com/reel/DIB-j7IOIch/?igsh=MTc1aGxicXA4am1hZg=='],
        ['nicho' => 'CRIADOR ESTRATEGISTA', 'url' => 'https://www.instagram.com/reel/DKh-3Q6ShjI/?igsh=MTdjdHprcWd3enhsdA=='],
        ['nicho' => 'SESSÃO DE FOTOS', 'url' => 'https://www.instagram.com/reel/DNJeTiVtm93/?igsh=aWdia3BzaDlsMzl4'],
        ['nicho' => 'FOTOGRAFIA', 'url' => 'https://www.instagram.com/reel/DK4gjScs6g7/?igsh=MWF2eHE4aHR4Z2xwag=='],
        ['nicho' => 'EDIÇÃO DE FOTOS', 'url' => 'https://www.instagram.com/reel/DJATVtipKGd/?igsh=MWptNnJnNTgxeXltdw=='],
        ['nicho' => 'PINTURA', 'url' => 'https://www.instagram.com/reel/DJ48t5URy5K/?igsh=MTZvMWg0YTN3c2F3dg=='],
        ['nicho' => 'BISCUIT', 'url' => 'https://www.instagram.com/reel/DJprpVTs0Xh/?igsh=MTgyZzhybW5rbjRzNA=='],
        ['nicho' => 'VELAS AROMÁTICAS', 'url' => 'https://www.instagram.com/reel/DJXIJlExnWW/?igsh=MWNwdm5tYXN1ZXMyOQ=='],
        ['nicho' => 'RESINA', 'url' => 'https://www.instagram.com/reel/DIhphYtMkOU/?igsh=dW4xanc4OXVyN3Vl'],
        ['nicho' => 'RESTAURAÇÃO DE BOTÕES AUTOMOTIVOS', 'url' => 'https://www.instagram.com/reel/DMv-VdKMHow/?igsh=cHMxb3YxbWV1OTZm'],
        ['nicho' => 'SABOARIA', 'url' => 'https://www.instagram.com/reel/DI1_jOrRTBN/?igsh=MTJvaWxteHk2azJsYQ=='],
        ['nicho' => 'MARCENARIA', 'url' => 'https://www.instagram.com/reel/DIbkAfas-8Y/?igsh=MTN0djBraTU2dmY1Mg=='],
        ['nicho' => 'IMPRESSORA 3D', 'url' => 'https://www.instagram.com/reel/DJ2W6IjyzN7/?igsh=OThsOWFsdTh1cm5r'],
        ['nicho' => 'LAVANDERIA DE TÊNIS', 'url' => 'https://www.instagram.com/reel/DMjLJwYRFpT/?igsh=bHlxcW5jOTlvcjdw'],
        ['nicho' => 'APICULTURA', 'url' => 'https://www.instagram.com/reel/DKzp3VtJB7n/?igsh=dGIydjA1cXZwcXkx'],
        ['nicho' => 'HAMBURGUERIA', 'url' => 'https://www.instagram.com/reel/DJX3Dm7oGVr/?igsh=emt0aHc5Z3l2N2tn'],
        ['nicho' => 'DERMATOLOGISTA', 'url' => 'https://www.instagram.com/reel/DN1dfZ_wrCc/?igsh=MTV3dGgxNm82dTlycw%3D%3D'],
        ['nicho' => 'CIRURGIA PLÁSTICA', 'url' => 'https://www.instagram.com/reel/DI9Zz2AO9Tx/?igsh=MWF2bjE1MHI0djU0Mg=='],
        ['nicho' => 'NEUROCIÊNCIA', 'url' => 'https://criadoresdofuturo.short.gy/juliasaraivavieira'],
        ['nicho' => 'INOVAÇÃO', 'url' => 'https://www.instagram.com/p/DB90pRrSerC/'],
        ['nicho' => 'DOCUMENTOS JURIDICOS', 'url' => 'https://www.instagram.com/p/C453_UeRMea/'],
        ['nicho' => 'REFORMA (ALUNA)', 'url' => 'https://www.instagram.com/p/DK5D5qqOM-E/'],
        ['nicho' => 'CRIADOR ESTRATEGISTA (ALUNA)', 'url' => 'https://www.instagram.com/reel/DOZ3vdkjB4y/?igsh=Y2t1Mmdoemsxb2Z0'],
        ['nicho' => 'UGC CREATOR', 'url' => 'https://www.instagram.com/p/DLQhfjfxX0F/'],
    ],
    'lo-fi' => [
        ['nicho' => 'AUTOCONFIANÇA', 'url' => 'https://www.instagram.com/p/DCmKfSGuiQU/'],
        ['nicho' => 'PATERNIDADE', 'url' => 'https://www.instagram.com/p/DCzxpjyR8P4/'],
        ['nicho' => 'NEURODIVERGENCIA', 'url' => 'https://www.instagram.com/p/DFrNqv9tMY1/'],
        ['nicho' => 'ALIMENTOS', 'url' => 'https://www.instagram.com/p/DKLFjFMShVj/'],
        ['nicho' => 'DERMATOLOGISTA', 'url' => 'https://www.instagram.com/p/DItKRrPOWXw/'],
        ['nicho' => 'FINANÇAS PESSOAIS', 'url' => 'https://www.instagram.com/p/DJtrEOMNK5L/'],
        ['nicho' => 'ESTUDOS', 'url' => 'https://www.instagram.com/p/DMX0HJpgEUp/'],
        ['nicho' => 'CIÊNCIA', 'url' => 'https://www.instagram.com/p/DObhLnVDYk-/'],
        ['nicho' => 'MUSCULAÇÃO', 'url' => 'https://www.instagram.com/p/DKZ950hu2uh/'],
        ['nicho' => 'LEITURA', 'url' => 'https://www.instagram.com/p/DOLu8LvkR91/'],
        ['nicho' => 'POLÍTICA', 'url' => 'https://www.instagram.com/p/DMgodJ4uL-y/'],
        ['nicho' => 'CONSUMO', 'url' => 'https://www.instagram.com/p/DM8vla-yRSY/'],
        ['nicho' => 'MÚSICA', 'url' => 'https://www.instagram.com/p/DJXr_MRge3z/'],
        ['nicho' => 'ATIVISMO SOCIAL E POLÍTICO', 'url' => 'https://www.instagram.com/p/DMIYfZeMhK0/'],
        ['nicho' => 'COMPORTAMENTO/RELAÇÕES', 'url' => 'https://www.instagram.com/p/DJWh-J8udtz/'],
        ['nicho' => 'SOCIAL', 'url' => 'https://www.instagram.com/p/DL-Yw3TOumA/'],
        ['nicho' => 'HUMOR', 'url' => 'https://www.instagram.com/p/DJAcIvROzfW/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DBHxjE3vxp0/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DNB9bWfuoBT/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DOGsoGOEXM5/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DLqMzXtyhs-/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DMxm22_t2m_/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DNHCwOTTKNv/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DOb4R2IEeOU/'],
    ],
    'cine' => [
        ['nicho' => 'RELIGIÃO', 'url' => 'https://www.instagram.com/reel/DIjJL5KsuC0/?igsh=MXhwbWtzYmxla3lreQ=='],
        ['nicho' => 'CORTES', 'url' => 'https://www.instagram.com/reel/DKQNGW6v8ZM/?igsh=MW1qNXJ6OXFxYW5jcA=='],
        ['nicho' => 'EMPREENDEDORISMO', 'url' => 'https://www.instagram.com/reel/DGY1008yNtg/?igsh=azZxeGcxNDQwOXVp'],
        ['nicho' => 'ESTRATÉGIA DE CONTEÚDO', 'url' => 'https://www.instagram.com/reel/DKhgu86RSoy/?igsh=MWR1NjJiN2cyN2Rkcw=='],
        ['nicho' => 'HUMOR', 'url' => 'https://www.instagram.com/p/DJSOPadvRRb/'],
        ['nicho' => 'CRIADOR ESTRATEGISTA', 'url' => 'https://www.instagram.com/reel/DGm_-dNSxHn/?igsh=MXVsbDRiMWkzbzFldg=='],
        ['nicho' => 'PROGRAMAÇÃO', 'url' => 'https://www.instagram.com/reel/DJhGuDbtByS/?igsh=ODZ3aTVka2FmbWN0'],
        ['nicho' => 'FILOSOFIA', 'url' => 'https://www.instagram.com/p/DN1WU1b5jDZ/'],
        ['nicho' => 'DESENVOLVIMENTO PESSOAL', 'url' => 'https://www.instagram.com/p/DOWC7bCDkwf/'],
        ['nicho' => 'REFLEXÃO', 'url' => 'https://www.instagram.com/p/DMjsFPvsFkH/'],
        ['nicho' => 'AMIZADE', 'url' => 'https://www.instagram.com/p/DKLd8NWRGnI/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DH1TX_tPss6/?igsh=OWtmajI0amxrdmVz'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKiI5WWRQxa/?igsh=ejA2dm5razJmd2Jj'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DHMaQ3CJcrO/?igsh=MTJ5ano4M3NrY3p6dg=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DGB5okNiJmE/?igsh=emRkZ3dqancydmpo'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DIH4UEbN5Uc/?igsh=eHh4czBpY3RseGF5'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DHzZz85S5K_/?igsh=MXpzaTYzN25xczRs'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DIYBYKrgnwi/?igsh=MWN5bHg5Y3kwdThtMw=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DIH9snGSqZg/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKOCSgEuvHo/?igsh=ZnJ0bTA0emM4ZWVz'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DOg3gGdAbR9/?igsh=MXNsNzB1azdxZGk2'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DI1Xvgsudt_/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DJh-pSlPWwn/'],
    ],
    'trivial' => [
        ['nicho' => 'FINANÇAS', 'url' => 'https://criadoresdofuturo.short.gy/brenonogueira'],
        ['nicho' => 'TERAPIA', 'url' => 'https://criadoresdofuturo.short.gy/fernandogodoi'],
        ['nicho' => 'CRIAÇÃO DE CONTEÚDO', 'url' => 'https://criadoresdofuturo.short.gy/sarahsnow'],
        ['nicho' => 'SUSHI', 'url' => 'https://criadoresdofuturo.short.gy/daisukisushi'],
        ['nicho' => 'COZINHA', 'url' => 'https://criadoresdofuturo.short.gy/juchenha'],
        ['nicho' => 'CORRIDA', 'url' => 'https://criadoresdofuturo.short.gy/danadonnelly'],
        ['nicho' => 'MARKETING E CINEMA', 'url' => 'https://criadoresdofuturo.short.gy/gabriellaviriato'],
        ['nicho' => 'RELACIONAMENTOS/TERAPIA', 'url' => 'https://criadoresdofuturo.short.gy/fernandacavalari2'],
        ['nicho' => 'HUMOR', 'url' => 'https://www.instagram.com/reel/DJXd1Cfy8rJ/?igsh=bm13czBiaWhmMnhm'],
        ['nicho' => 'POSICIONAMENTO CORPORATIVO', 'url' => 'https://www.instagram.com/p/C_tYXQ-yk4A/'],
        ['nicho' => 'EMAGRECIMENTO', 'url' => 'https://www.instagram.com/p/DBlu9uGO5VM/'],
        ['nicho' => 'FINANÇAS PESSOAIS', 'url' => 'https://www.instagram.com/p/DHyuNeuxCWb/'],
        ['nicho' => 'PSICOLOGIA', 'url' => 'https://www.instagram.com/p/DHwcU91xolV/'],
        ['nicho' => 'FUTEBOL FEMININO', 'url' => 'https://www.instagram.com/p/DMV9zXHvQJt/'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/deboraferreira'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/carolloback'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/jeffersonsouza'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/fernandacavalari'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/gabimoretti'],
    ],
    'experimento-social' => [
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DMvWWgJijjU/?igsh=Y3p2ODVnejZwdXkx'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DCjcihWzQlM/?igsh=b3Q2amxnbnBpMmho'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/C-A2Fxtoaez/?igsh=amp0NHgzbWdicjRs'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DI27ycpR4lf/?igsh=OXd4eWFqNWIzazd6'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DMNzhzNuu9z/?igsh=azd1djI0aGJ6cTlk'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DImKGxWPBcR/?igsh=MThkd2hsNW82aTl2Mw=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKfRvJXgCVb/?igsh=MWd5b2c5NzUzNHBjNw=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DM7r323ogN-/?igsh=MTR5eXdkNWh1aDhqYQ=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DNanx-hAFDr/?igsh=MTd1NXhxbDV2YW5veg=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DJNKudWRNST/?igsh=MXU2ZzRjZ3d0c2hpdQ=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DH_RjRzu6HL/?igsh=MTd1azRtN2IwZDB1dg=='],
        ['nicho' => 'GAMES', 'url' => 'https://www.instagram.com/reel/DAHOdDsyYHB/?igsh=MWZxZ2JvMTl1MWhjZw=='],
        ['nicho' => 'PSICOLOGIA', 'url' => 'https://www.instagram.com/reel/DMQOQgGsDV0/?igsh=MWdwaTJ3eDhhbzh3NQ=='],
        ['nicho' => 'EMPREENDEDORISMO', 'url' => 'https://www.instagram.com/reel/DLNj6OqAiAz/?igsh=MWRuaDA3OW44czQzYw=='],
        ['nicho' => 'RELACIONAMENTO', 'url' => 'https://www.instagram.com/reel/DI2BIocSobE/?igsh=NTFmaDI2M3BhbnB6'],
        ['nicho' => 'FOTOGRAFIA', 'url' => 'https://www.instagram.com/reel/DMA_iYpss3r/?igsh=MXB2ZnV0MzgwZXlxdw=='],
        ['nicho' => 'PROJETO SOCIAL', 'url' => 'https://www.instagram.com/reel/DMN03gLO14j/?igsh=MWNqaTFqamR0YnR3aw=='],
        ['nicho' => 'PUBLI', 'url' => 'https://www.instagram.com/reel/DIeMBV3p3zH/?igsh=dDExbTlxdXZpeGZt'],
        ['nicho' => 'HUMOR/PEGADINHA', 'url' => 'https://www.instagram.com/reel/DLwCmNsAtp9/?igsh=MWc1ODY4ZThvZDd0OA=='],
        ['nicho' => 'COMIDA', 'url' => 'https://www.instagram.com/reel/DGfd2sQN5Zd/?igsh=MWttMXlqb3Y1NzZuYQ=='],
        ['nicho' => 'POLÍTICA', 'url' => 'https://www.instagram.com/reel/DLNjpm-RQO6/?igsh=MWVuN24zaGI4MGpzbg=='],
        ['nicho' => 'PODCAST', 'url' => 'https://www.instagram.com/reel/DLAKslLRbjl/?igsh=MXJlbjh3b2ZhODVnbg=='],
        ['nicho' => 'GEEK', 'url' => 'https://www.instagram.com/reel/DGVtF7KppuG/?igsh=MWlrYWN2NTNncm9wMg=='],
        ['nicho' => 'MEME', 'url' => 'https://www.instagram.com/reel/DJz3upgvOVg/?igsh=MTdwMGphamZ6cm96MA=='],
        ['nicho' => 'GEOGRAFIA', 'url' => 'https://www.instagram.com/reel/DLplV7Oxd2D/?igsh=MTZ6bjAxdGk4b2c1MA=='],
        ['nicho' => 'CRISTIANISMO', 'url' => 'https://www.instagram.com/reel/DOE2QChjUlG/?igsh=OWFkdXUzZ3B6b28x'],
        ['nicho' => 'MÚSICA', 'url' => 'https://www.instagram.com/reel/DMxv48YgR5z/?igsh=MTZpcHFxdDl1Yzk5cQ=='],
        ['nicho' => 'RELIGIÃO', 'url' => 'https://www.instagram.com/reel/DMi4f-yR5g8/?igsh=MzBjdzJ0YjZxN29l'],
        ['nicho' => 'DESIGN', 'url' => 'https://www.instagram.com/reel/DJcu5DoRHic/?igsh=MW43cm16MjU0NHYwdw=='],
        ['nicho' => 'LEITURA', 'url' => 'https://www.instagram.com/reel/DIZqpn3P32i/?igsh=dDRmMGpoM2c3aGdt'],
        ['nicho' => 'VENDAS', 'url' => 'https://www.instagram.com/reel/DDUldMKu3L1/'],
        ['nicho' => 'ADESTRAMENTO', 'url' => 'https://www.instagram.com/reel/DN_HqA0kW0m/?igsh=MWJ0dzlqeXYydjBmZg=='],
        ['nicho' => 'EDUCAÇÃO', 'url' => 'https://www.instagram.com/reel/DJXeEetBzpb/?igsh=OWl1OGRyMHJ1N2Zm'],
        ['nicho' => 'VENDEDOR DE RUA', 'url' => 'https://www.instagram.com/reel/DNB1gHWSbZA/?igsh=MWt5d2RwZnJramZqNQ=='],
    ],
    'dialogo' => [
        ['nicho' => 'FITNESS', 'url' => 'https://criadoresdofuturo.short.gy/marikruger1'],
        ['nicho' => 'SAÚDE', 'url' => 'https://criadoresdofuturo.short.gy/marikruger2'],
        ['nicho' => 'NAMORO', 'url' => 'https://criadoresdofuturo.short.gy/leohwan1'],
        ['nicho' => 'FINANÇAS', 'url' => 'https://criadoresdofuturo.short.gy/barbararegina1'],
        ['nicho' => 'ACADEMIA', 'url' => 'https://criadoresdofuturo.short.gy/daianaparisato1'],
        ['nicho' => 'FILOSOFIA', 'url' => 'https://criadoresdofuturo.short.gy/leohwan2'],
        ['nicho' => 'RELACIONAMENTO', 'url' => 'https://criadoresdofuturo.short.gy/viniqueiroz1'],
        ['nicho' => 'TERAPIA', 'url' => 'https://criadoresdofuturo.short.gy/draneusa1'],
        ['nicho' => 'HUMOR/ROTINA', 'url' => 'https://criadoresdofuturo.short.gy/brunapinheiro1'],
        ['nicho' => 'DESENVOLVIMENTO PESSOAL', 'url' => 'https://criadoresdofuturo.short.gy/momo1'],
        ['nicho' => 'DESENVOLVIMENTO PESSOAL', 'url' => 'https://criadoresdofuturo.short.gy/tressunistephanie'],
        ['nicho' => 'TDAH', 'url' => 'https://criadoresdofuturo.short.gy/raizanoah1'],
        ['nicho' => 'ATENDIMENTO/NEGÓCIOS', 'url' => 'https://criadoresdofuturo.short.gy/julianaguagliani1'],
        ['nicho' => 'CORPORATIVO', 'url' => 'https://criadoresdofuturo.short.gy/anandraman1'],
        ['nicho' => 'MATERNIADE', 'url' => 'https://criadoresdofuturo.short.gy/gabriellefarias'],
        ['nicho' => 'FEMINILIDADE', 'url' => 'https://criadoresdofuturo.short.gy/barbararegina2'],
        ['nicho' => 'COMUNICAÇÃO E POSICIONAMENTO', 'url' => 'https://www.instagram.com/p/DHv4mLeuL3X/'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/marikruger'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/barbararegina'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/leohwan'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/draneusa'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/raizanoah'],
    ],
    'conflito-situacional' => [
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKxfgI9M_pI/?igsh=MXBqbWdtM2p4OWpteQ=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKOpf6ISyOm/?igsh=Y3k1eTk3NzVuZXFl'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DFvxNoiTqyC/?igsh=MTVsNmt2dTdyY3hybQ=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DMjVBVVo6Qn/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/drkaiquetorres/reels/'],
        ['nicho' => 'MÚSICA', 'url' => 'https://www.instagram.com/reel/DKLxnjixWGG/?igsh=MXF4dDd3eGQyamU4cA=='],
        ['nicho' => 'MÚSICA', 'url' => 'https://www.instagram.com/reel/DGJKEuyizrS/?igsh=MWJraWtwb2t3d29obw=='],
        ['nicho' => 'POLÍTICA', 'url' => 'https://www.instagram.com/reel/DMsbpt8MT2-/?igsh=dmE5bXFtNHhkbmZi'],
        ['nicho' => 'PUBLI', 'url' => 'https://www.instagram.com/reel/DJuTxmyNO3U/?igsh=NTAweTZ1bjg0dTdv'],
        ['nicho' => 'MARCA DE ROUPA', 'url' => 'https://www.instagram.com/reel/DJy5yJUMByw/?igsh=MWpzM3doZjFxZXk4aA=='],
        ['nicho' => 'ALIMENTO', 'url' => 'https://www.instagram.com/reel/DJyXswtsUSS/?igsh=MTE5MDhxZnJpaGNpcw=='],
        ['nicho' => 'CRISTIANISMO', 'url' => 'https://www.instagram.com/reel/DGOf3PKR_tk/?igsh=M3NlbXU5cnRvMjNr'],
        ['nicho' => 'LOJA DE TÊNIS', 'url' => 'https://www.instagram.com/reel/DHECHQIqTaH/?igsh=MTF1cHprcDFrbmhvcw=='],
        ['nicho' => 'BARBEARIA', 'url' => 'https://www.instagram.com/reel/DGU-I88zBuj/?igsh=MWpiempha2Y4azk5ZA=='],
        ['nicho' => 'MENTALIDADE', 'url' => 'https://www.instagram.com/p/DJ4ukxPy8xh/'],
        ['nicho' => 'UNHAS', 'url' => 'https://www.instagram.com/p/DNOkTqgxhTn/'],
        ['nicho' => 'CAFETERIA', 'url' => 'https://www.instagram.com/p/DOOvkUXAFwI/'],
        ['nicho' => 'LOJA', 'url' => 'https://www.instagram.com/p/DMBaVDfxe_h/'],
    ],
    'palestrinha' => [
        ['nicho' => 'HUMOR', 'url' => 'https://criadoresdofuturo.short.gy/brendaercolani'],
        ['nicho' => 'SAÚDE', 'url' => 'https://criadoresdofuturo.short.gy/marikruger6'],
        ['nicho' => 'CARROS', 'url' => 'https://criadoresdofuturo.short.gy/jhennykeller'],
        ['nicho' => 'LITERATURA', 'url' => 'https://www.instagram.com/p/DMtScSIpjkw/'],
        ['nicho' => 'REGIONALISMO', 'url' => 'https://www.instagram.com/reel/DNVxsX9u9n3/?igsh=Z2c0a2s4b2JleXly'],
        ['nicho' => 'LOJA DE PRESENTES', 'url' => 'https://www.instagram.com/reel/DHg_jQwNqZQ/?igsh=MXVrYnA4YXRuYTc0dQ=='],
        ['nicho' => 'TECNOLOGIA', 'url' => 'https://www.instagram.com/reel/DOJNmx4DhUL/?igsh=cHI1MjN2djkxd2Rl'],
        ['nicho' => 'NAMORO', 'url' => 'https://www.instagram.com/reel/DHgttYbOT7x/?igsh=MXZyd3Rsbmdlem5rbA=='],
        ['nicho' => 'DESENVOLVIMENTO PESSOAL', 'url' => 'https://www.instagram.com/reel/DLGm3YdtXl_/?igsh=MWJ0bmpqOTdzd3h1MA=='],
        ['nicho' => 'FINANÇAS', 'url' => 'https://www.instagram.com/reel/DFiucv6JQKZ/'],
        ['nicho' => 'AMIZADE', 'url' => 'https://www.instagram.com/reel/DIJaEwDMvXv/?igsh=MWk3bGt1eXNsaGM0OQ%3D%3D'],
        ['nicho' => 'MATERNIDADE', 'url' => 'https://www.instagram.com/p/DJZ7mKmxioF/'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/marikruger5'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reels/DMapn1bRsuV/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DOMRJxjEcNZ/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/p/DM_fLPruyM9/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DKIZlnWx-g3/?igsh=MWlsNGFxaGY1dzhqMQ=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DLBJ9bDy8s_/?igsh=MTA0bnZwbHh0cHptaw=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DNZTOKnukKa/?igsh=MThibmMxcXhqYWhkNg=='],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DMBx90LNdP0/?igsh=MW9waGNxZDlpbXl4dA=='],
    ],
    'tela-dividida' => [
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/hanahfranklin5'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/rodrigogoes'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DMaKp1iRYBJ/'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/DHtL7NjsuO4/?igsh=bmN0ZnRrM2Vra3Js'],
        ['nicho' => '', 'url' => 'https://www.instagram.com/reel/C_cv9TROZcU/?igsh=dmt6NDFkdXhqOHI1'],
        ['nicho' => 'SAÚDE MENTAL', 'url' => 'https://criadoresdofuturo.short.gy/rafaelasarti'],
        ['nicho' => 'ACADEMIA', 'url' => 'https://criadoresdofuturo.short.gy/rodrigogoes2'],
        ['nicho' => 'ESTÉTICA', 'url' => 'https://www.tiktok.com/@dr.urielnascimento/video/7419126217284062470?q=ANALISE&t=1743725450289'],
        ['nicho' => 'COACH', 'url' => 'https://www.instagram.com/reel/DMhwkkIOT9I/'],
        ['nicho' => 'MILITANCIA', 'url' => 'https://www.instagram.com/p/DGGqT7xJ1mn/'],
        ['nicho' => 'PSICOLOGIA', 'url' => 'https://www.instagram.com/p/DML5pksPHcj/'],
        ['nicho' => 'CONDICIONAMENTO FÍSICO', 'url' => 'https://www.instagram.com/p/DMDO9pORmJH/'],
        ['nicho' => 'MÚSICA', 'url' => 'https://www.instagram.com/p/DKcrJUEPI7E/'],
        ['nicho' => 'NEGÓCIOS', 'url' => 'https://www.instagram.com/reel/DM_WVbKR4h6/'],
        ['nicho' => 'PRODUTOS NATURAIS', 'url' => 'https://www.instagram.com/p/DKMXDd6vmts/'],
        ['nicho' => 'GESTÃO DE MARCAS', 'url' => 'https://www.instagram.com/p/DDiHvusRKaK/'],
        ['nicho' => 'PROJETOS', 'url' => 'https://www.instagram.com/p/DGTDY27xh_U/'],
        ['nicho' => 'LEITURA/COMUNICAÇÃO', 'url' => 'https://www.instagram.com/p/DJASrRuxKPv/'],
        ['nicho' => 'FILOSOFIA (ALUNO)', 'url' => 'https://www.instagram.com/reel/DMOblJmgnm0/'],
        ['nicho' => 'POSICIONAMENTO', 'url' => 'https://www.instagram.com/reels/DOo091TieWC/'],
        ['nicho' => 'EXPRESSÃO FACIAL E CORPORAL', 'url' => 'https://www.instagram.com/reel/DNN_AAxtPbx/?igsh=MWNsemd1bmgycGlr'],
    ],
    'caixinha-polemica' => [
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/gutogalamba'],
        ['nicho' => '', 'url' => 'https://criadoresdofuturo.short.gy/cintiachagas'],
        ['nicho' => 'ETIQUETA', 'url' => 'https://criadoresdofuturo.short.gy/cintiachagas2'],
        ['nicho' => 'MEDICINA', 'url' => 'https://criadoresdofuturo.short.gy/renanbotelho'],
        ['nicho' => 'SEXÓLOGA', 'url' => 'https://criadoresdofuturo.short.gy/catiadamasceno'],
        ['nicho' => 'TREINO', 'url' => 'https://criadoresdofuturo.short.gy/gutogalamba2'],
        ['nicho' => 'NUTRIÇÃO', 'url' => 'https://criadoresdofuturo.short.gy/isabellalacerda'],
        ['nicho' => 'HUMOR', 'url' => 'https://criadoresdofuturo.short.gy/lactea'],
        ['nicho' => 'INVESTIMENTOS', 'url' => 'https://criadoresdofuturo.short.gy/brunoperini'],
        ['nicho' => 'NEGÓCIOS', 'url' => 'https://criadoresdofuturo.short.gy/geracaodevalor'],
    ],
];
